title: "ArchEHR-QA 2026 <i>(\"Archer\")</i>"
logo: /assets/img/logo.svg
short_title: "ArchEHR-QA 2026: CL4Health @LREC Shared Task"
description: <a href='https://bionlp.nlm.nih.gov/cl4health2026/'>CL4Health @LREC 2026 Shared Task</a> on grounded question answering (QA) from electronic health records (EHRs)
show_downloads: false
remote_theme: pages-themes/minimal@v0.2.0
url: https://archehr-qa.github.io/
plugins:
- jekyll-remote-theme
- jekyll-sitemap
github:
  is_project_page: false
  is_user_page: false

defaults:
  - scope:
      path: ""
    values:
      logo: /assets/img/logo.svg
  - scope:
      path: "2025"
    values:
      logo: ""
      site_title: "ArchEHR-QA 2025 <i>(pronounced \"Archer\")</i>:<br>Shared Task on Grounded Electronic Health Record Question Answering"
      short_title: "ArchEHR-QA 2025: BioNLP@ACL Shared Task"
      description: "<a href='https://aclweb.org/aclwiki/BioNLP_Workshop'>BioNLP @ACL 2025 Shared Task</a> on grounded question answering (QA) from electronic health records (EHRs)"